#!/usr/bin/env bash

# Save current directory
cygwin=false
case "`uname`" in
  CYGWIN*) cygwin=true;;
esac

# resolve links - $0 may be a softlink
PRG="$0"

while [ -h "$PRG" ] ; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`/"$link"
  fi
done

# Set the current directory to the installation directory
INSTALLDIR=`dirname "$PRG"`

if [ -x "$INSTALLDIR/jre/bin/java" ]; then
 JAVA_CMD=$INSTALLDIR/jre/bin/java
else
 # Use JAVA_HOME if it is set
 if [ -z "$JAVA_HOME" ]; then
  JAVA_CMD=java
 else
  JAVA_CMD=$JAVA_HOME/bin/java
 fi
fi

CP="$INSTALLDIR/lib/*:$INSTALLDIR/script-lib/*"

if $cygwin; then
  CP=$(cygpath -pw "$CP")
fi

"$JAVA_CMD" -cp "$CP" org.beyondpn.redis.migration.Main "$@"

# Exit using the same code returned from Java
exit $?